version: "3.9"

volumes:
    postgres_data:
services:
  web:
    container_name: dev_backend
    build: .
    restart: always
    env_file: .env
    command: gunicorn sandglass.wsgi:application --bind 0.0.0.0:5000
    volumes:
     - .:/app
#     - static_volume:/app/static
    depends_on:
     - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 5432:5432
