# Generated by Django 3.2.5 on 2021-07-28 14:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=7)),
                ('signatime', models.DurationField(default=datetime.timedelta)),
                ('designtime', models.DurationField(default=datetime.timedelta)),
                ('packagetime', models.DurationField(default=datetime.timedelta)),
                ('description', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer.manager')),
                ('prepresser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=7)),
                ('jobtype', models.CharField(choices=[('Signa', 'Signa'), ('Design', 'Design'), ('Package', 'Package')], max_length=12)),
                ('time', models.DateTimeField(auto_now_add=True, help_text='Время нажатия на кнопку')),
                ('button', models.CharField(choices=[('start', 'start'), ('stop', 'stop')], max_length=10)),
                ('description', models.CharField(max_length=100, null=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timer.manager')),
                ('prepresser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
