# Generated by Django 3.2.5 on 2021-07-30 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_auto_20210730_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timer.manager'),
        ),
    ]
