# Generated by Django 3.2.5 on 2021-07-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_auto_20210730_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawdata',
            old_name='description',
            new_name='jobnote',
        ),
        migrations.RenameField(
            model_name='timing',
            old_name='description',
            new_name='jobnote',
        ),
    ]
