# Generated by Django 3.2.6 on 2021-08-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0004_auto_20210730_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='asystem_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
