# Generated by Django 3.2.6 on 2021-08-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0005_manager_asystem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='email',
            field=models.EmailField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
