# Generated by Django 3.2.6 on 2021-08-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0006_manager_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='is_order',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timing',
            name='is_order',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
