# Generated by Django 3.2.6 on 2021-08-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0007_auto_20210831_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='timing',
            name='design_is_paid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
