# Generated by Django 3.2.6 on 2021-08-31 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0008_timing_design_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawdata',
            name='is_order',
        ),
    ]
