# Generated by Django 3.2.6 on 2021-08-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0009_remove_rawdata_is_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='is_order',
            field=models.BooleanField(help_text='Являлась ли работа изначально заказом или работой от менеджера'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='order',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
