# Generated by Django 3.2.6 on 2021-08-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0010_auto_20210831_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='design_is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
