# Generated by Django 3.2.6 on 2021-09-01 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0011_alter_timing_design_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timer.manager'),
        ),
    ]
